kind: pipeline
type: docker
name: docker

platform:
  arch: arm64
  os: linux

trigger:
  ref:
  - refs/heads/master
  event:
    exclude:
    - pull_request

steps:
- name: get version
  image: apline/git
  commands:
  - git rev-parse --short HEAD > .tags
- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: exepir1t/cf-ddns
