kind: pipeline
type: docker
name: docker

platform:
  arch: arm64
  os: linux

trigger:
  event:
    exclude:
    - pull_request

steps:
- name: set nigntly version
  image: busybox
  commands:
  - echo "nightly" > .tags
  when:
    branch:
    - develop
    event:
    - cron
    cron:
    - nightly

- name: set release version
  image: alpine/git
  commands:
  - git tag --points-at HEAD > .tags
  - echo ",latest" >> .tags
  when:
    branch:
    - master

- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: exepir1t/cf-ddns
