apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cf-ddns.fullname" . }}
  labels:
    {{- include "cf-ddns.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.provider.parameters }}
  DDNS_{{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  DDNS_PROVIDER: {{ .Values.provider.type | quote }}
  DDNS_SOURCE: {{ .Values.source.type | quote }}
