{{- if and .Values.serviceAccount.create (eq .Values.source.type "kubernetes") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cf-ddns.serviceAccountName" . }}
  labels:
    {{- include "cf-ddns.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
{{- end }}
