{{- if and .Values.serviceAccount.create (eq .Values.source.type "kubernetes") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cf-ddns.serviceAccountName" . }}
  labels:
    {{- include "cf-ddns.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "cf-ddns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cf-ddns.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
